language: go
install: go get -u -v github.com/spf13/hugo

branches:
    only:
        gh-pages-hugo

script:
    - hugo

after_success:
    - echo "ponylang.org" > ./public/CNAME
    - if [[ $TRAVIS_BRANCH == 'gh-pages-hugo' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
        rev=$(git rev-parse --short HEAD)
        git add -A
        git commit -m "Update to revision $rev"
        git push origin gh-pages-hugo
        git subtree push --prefix=public $GH_TOKEN@github.com:ponylang/ponylang.github.io master
      fi;
