language: go
install: brew install hugo

branches:
    only:
        source
matrix:
  include:
    - os: osx

script:
    - hugo version;
    - hugo;

after_success:
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "source" && bash deploy.sh
