language: go
install: go get -u -v github.com/spf13/hugo

branches:
    only:
        gh-pages-hugo

script:
    - hugo

after_success:
    - echo "ponylang.org" > ./public/CNAME
    - if [[ $TRAVIS_BRANCH == 'gh-pages-hugo' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
        rev=$(git rev-parse --short HEAD);

        git init;
        git config user.name "Sean T. Allen";
        git config user.email "sean@monkeysnatchbanana.com";
        git remote add upstream "https://$GH_TOKEN@github.com/ponylang/ponylang.github.io";
        git fetch upstream;
        git reset upstream/master;

        cd public;

        touch .;

        git add -A .;
        git commit -m "rebuild pages at ${rev}";
        git push -q upstream HEAD:master;
      fi;
