baseurl = "http://www.ponylang.org"
languageCode = "en-us"
title = "Pony"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id

[params]
	# General information
	description = "Pony - High Performance Actor Programming"
	copyright = "Pony Developers"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/ponylang/ponyc"

	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "brown"
    	accent  = "grey"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = "ponylang"
	github  = "ponylang"

[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Discover"
	url    = "discover/"
	weight = 10

[[menu.main]]
	name   = "Learn"
	url    = "learn/"
	weight = 20

[[menu.main]]
	name   = "Contribute"
	url    = "contribute/"
	weight = 30

[[menu.main]]
	name   = "Reference"
	url    = "reference/"
	weight = 40

[[menu.main]]
	name   = "Community"
	url    = "community/"
	weight = 50

[[menu.main]]
	name   = "Blog"
	url    = "blog/"
	weight = 60

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[permalinks]
  blog = "/blog/:year/:month/:title/"

